"""Add title to chat_messages table

Revision ID: f77488db2dbd
Revises: a2d40520b02b
Create Date: 2025-12-10 14:33:50.934855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77488db2dbd'
down_revision: Union[str, Sequence[str], None] = 'a2d40520b02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('title', sa.String(length=200), nullable=True, comment='Conversation title (stored on first message of thread)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'title')
    # ### end Alembic commands ###
